<?php

namespace Application\Repository;

use Application\Entity\Film;
use Doctrine\ORM\EntityRepository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method Film[] findAll()
 */
class FilmRepository extends EntityRepository
{
}
