<?php

use Contact\Form\ContactForm;
use Zend\Form\View\Helper\FormLabel;

/** @var ContactForm $form */
$form = $this->form;
$form
    ->prepare()
    ->setAttributes([
        'action' => $this->url('contact'),
        'method' => 'post',
        'class' => 'form'
    ]);

/** @var FormLabel $formLabel */
$formLabel = $this->plugin('formLabel');
$name = $form->get('name');
$email = $form->get('email');

?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<?php
echo $this->partial('flashbag.phtml', ['flash' => $this->flashMessenger()]);

?>
<h1>Contact</h1>
<?= $this->form()->openTag($form); ?>
<div class="form-group">
    <?= $formLabel($name); ?>
    <?= $this->formInput($name); ?>
    <?= $this->formElementErrors($name); ?>
</div>

<div class="form-group">
    <?= $formLabel($email); ?>
    <?= $this->formInput($email); ?>
    <?= $this->formElementErrors($email); ?>
</div>

<?= $this->formElement($form->get('security')) ?>
<?= $this->formElement($form->get('send')) ?>
<?= $this->form()->closeTag() ?>

</body>
</html>