<?php
use Application\Entity\Film;

?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ping Index</title>
</head>
<body>
<?php

/** @var Film $film */
foreach ($this->films as $film) {
    foreach ((array)$film as $key => $item) {
        $key = str_replace(get_class($film), "", $key);
        echo "$key : $item <br>";
    }

}
?>

</body>
</html>